---
- name: Install Python-pip, Prometheus, Grafana, and ELK Stack
  hosts: k8s-master
  become: true
  environment:
    KUBECONFIG: ~/.kube/config
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install python3-pip
      apt:
        name: 
          - python3-pip
          - python3-setuptools
        state: present

    - name: Install Python requirements
      pip:
        name:
          - kubernetes
          - openshift
        state: present

    - import_tasks: ../roles/prometheus.yaml
    - import_tasks: ../roles/grafana.yaml
    - import_tasks: ../roles/elk.yaml