apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: dev
data:
  BACKEND_URL: "http://backend-service.dev.svc.cluster.local:5000"
  DATABASE_URI: "postgresql://ecommerce:testing123@database-service.dev.svc.cluster.local:5432/ecommerce_db"
