apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-frontend-config
  namespace: dev
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      paths:
        - /var/log/nginx/*.log
      fields:
        app: frontend
      fields_under_root: true

    processors:
      - add_kubernetes_metadata:
          host: ${NODE_NAME}
          matchers:
          - logs_path:
              logs_path: "/var/log/nginx/"

    setup.template.name: "frontend-logs"
    setup.template.pattern: "frontend-logs-*"
    setup.ilm.enabled: true
    setup.kibana:
      host: "https://kibana-kibana.logging.svc.cluster.local:5601"
      username: "elastic"
      password: "xxx"
      ssl.enabled: true
      ssl.verification_mode: none

    output.elasticsearch:
      hosts: ["https://elasticsearch-master.logging.svc.cluster.local:9200"]
      username: "elastic"
      password: "xxx"
      index: "frontend-logs-%{+yyyy.MM.dd}"
      ssl.enabled: true
      ssl.verification_mode: none

